### ISSUE TITLE
HTTP Code 400 for Missing Parameters ?

### ISSUE THREAD

**Issue by vaidiep** [thecodingmachine/mvc.splash#22]
If a parameter is not passed when calling an URL, an exception, "Missing Parameter", is thrown which returns a 500 HTTP error. I think that it would be preferable to return a 400 HTTP error "Bad request" because it is a client error, not a server one. Similarly, we can do the same thing for the malformed parameters.

Furthermore, I think that we should return a 405 HTTP error "Method Not Allowed" if the URL exists but not for the method used (GET, PUT, POST, ..).

**Comment by moufmouf** [comment]
Done in Splash 8
