### ISSUE TITLE
Error with CSRF_ALLOWED_DOMAIN_NAMES

### ISSUE THREAD

**Issue by vaidiep** [thecodingmachine/mvc.splash#28]
During the installation process, the instance "TheCodingMachine\Middlewares\CsrfHeaderCheckMiddleware" is created before the config variable "CSRF_ALLOWED_DOMAIN_NAMES".
This result an error "Undefined constant .." in the Mouf status page

We must save this instance again (i.e. after the config variable "CSRF_ALLOWED_DOMAIN_NAMES" is set) to solve the error.

**Comment by moufmouf** [comment]
Fixed in #35
